import Navbar from "@/components/global/navbar"
import Footer from "@/components/global/footer"
import { Button } from "@/components/ui/button"
import { CheckCircle2 } from "lucide-react"
import Link from "next/link"

const freeFeatures = [
  "AI Chat-based Financial Advice",
  "Savings Rate Suggestions",
  "Basic Investment Allocation Guidance",
  "Debt Payoff Strategy Overview",
  "Limited Chat History",
]

const plusFeatures = [
  "Everything in Free, plus:",
  "Voice Calls with Financial Assistant",
  "Personalized Spending Challenges & Tracking",
  "Proactive Accountability Check-ins",
  "In-depth Financial Analysis & Reports",
  "Unlimited Chat History",
  "Priority Support",
]

export default function PricingPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      <main className="flex-grow py-12 md:py-20 bg-gradient-to-b from-background via-muted/20 to-background">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12 md:mb-16">
            <h1 className="text-4xl sm:text-5xl font-extrabold tracking-tight">
              Find the <span className="text-primary">clever</span> Plan That's Right For You
            </h1>
            <p className="mt-4 text-lg sm:text-xl text-muted-foreground max-w-2xl mx-auto">
              Start for free, and unlock powerful financial tools with clever Plus.
            </p>
          </div>

          <div className="flex flex-col lg:flex-row justify-center items-stretch gap-8 max-w-4xl mx-auto">
            {/* Free Tier Card */}
            <div className="flex-1 bg-background p-8 rounded-xl shadow-xl border flex flex-col">
              <h2 className="text-2xl font-semibold mb-2">Free</h2>
              <p className="text-muted-foreground mb-6">Essential AI financial guidance to get you started.</p>
              <p className="text-4xl font-bold mb-1">
                $0 <span className="text-lg font-normal text-muted-foreground">/ month</span>
              </p>
              <Button asChild variant="outline" className="w-full mt-6 mb-8">
                <Link href="/auth/signup">Get Started for Free</Link>
              </Button>
              <ul className="space-y-3 text-muted-foreground flex-grow">
                {freeFeatures.map((feature, idx) => (
                  <li key={idx} className="flex items-start">
                    <CheckCircle2 className="h-5 w-5 text-green-500 mr-2 mt-0.5 shrink-0" />
                    <span>{feature}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Clever Plus Tier Card */}
            <div className="flex-1 bg-primary text-primary-foreground p-8 rounded-xl shadow-2xl border border-primary flex flex-col relative overflow-hidden">
              <div className="absolute top-0 right-0 bg-yellow-400 text-yellow-900 px-3 py-1 text-xs font-semibold transform rotate-45 translate-x-1/3 translate-y-1/3 origin-top-left">
                BEST VALUE
              </div>
              <h2 className="text-2xl font-semibold mb-2">clever Plus</h2>
              <p className="opacity-90 mb-6">The ultimate toolkit for financial mastery and peace of mind.</p>
              <p className="text-4xl font-bold mb-1">
                $4.99 <span className="text-lg font-normal opacity-80">/ month</span>
              </p>
              <Button
                variant="secondary"
                className="w-full mt-6 mb-8 bg-primary-foreground text-primary hover:bg-primary-foreground/90"
              >
                Upgrade to Plus (Coming Soon)
              </Button>
              <ul className="space-y-3 opacity-95 flex-grow">
                {plusFeatures.map((feature, idx) => (
                  <li key={idx} className="flex items-start">
                    <CheckCircle2 className="h-5 w-5 text-green-300 mr-2 mt-0.5 shrink-0" />
                    <span>{feature}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
          <p className="text-center text-sm text-muted-foreground mt-12 max-w-3xl mx-auto">
            <strong>Disclaimer:</strong> clever llm provides AI-powered financial information and education. It is not a
            registered investment advisor, broker/dealer, or legal/tax advisor. All financial opinions expressed by
            clever are generated by an AI model based on available data and are for educational purposes only. They
            should not be considered as professional financial advice. Always consult with a qualified financial
            professional before making any financial decisions.
          </p>
        </div>
      </main>
      <Footer />
    </div>
  )
}
